version: '3.4'
services:
  taco-api:
    build:
      context: .
      dockerfile: dev.dockerfile
      target: micronaut
    working_dir: /code
    ports:
      - "80:8080"
    volumes:
      - .:/code:rw