version: '3.4'
services:
  build:
    build:
      context: .
      dockerfile: dev.dockerfile
      target: micronaut
    working_dir: /code
    volumes:
      - .:/code:rw
    command: ./gradlew --no-daemon clean build
  run:
    build:
      context: .
      dockerfile: dev.dockerfile
      target: micronaut
    working_dir: /code
    ports:
      - "80:8080"
    volumes:
      - .:/code:rw
    command: ./gradlew --no-daemon clean run